/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import {IModPack} from './IModPack';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {IModPack};
export const IModPackSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "definitions": {
    "IGamebryoRules": {
      "defaultProperties": [
      ],
      "properties": {
        "groups": {
          "items": {
            "$ref": "#/definitions/IUserlistEntry"
          },
          "type": "array"
        },
        "plugins": {
          "items": {
            "$ref": "#/definitions/IUserlistEntry"
          },
          "type": "array"
        }
      },
      "required": [
        "plugins"
      ],
      "type": "object"
    },
    "IModPackInfo": {
      "defaultProperties": [
      ],
      "properties": {
        "author": {
          "type": "string"
        },
        "authorUrl": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "domainName": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "author",
        "authorUrl",
        "description",
        "domainName",
        "name"
      ],
      "type": "object"
    },
    "IModPackMod": {
      "defaultProperties": [
      ],
      "properties": {
        "author": {
          "type": "string"
        },
        "choices": {
        },
        "details": {
          "$ref": "#/definitions/IModPackModDetails"
        },
        "domainName": {
          "type": "string"
        },
        "hashes": {
        },
        "name": {
          "type": "string"
        },
        "optional": {
          "type": "boolean"
        },
        "source": {
          "$ref": "#/definitions/IModPackSourceInfo"
        },
        "version": {
          "type": "string"
        }
      },
      "required": [
        "domainName",
        "name",
        "optional",
        "source",
        "version"
      ],
      "type": "object"
    },
    "IModPackModDetails": {
      "defaultProperties": [
      ],
      "properties": {
        "type": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "IModPackModRule": {
      "defaultProperties": [
      ],
      "properties": {
        "reference": {
          "$ref": "#/definitions/IModReference"
        },
        "source": {
          "$ref": "#/definitions/IModReference"
        },
        "type": {
          "$ref": "#/definitions/RuleType"
        }
      },
      "required": [
        "reference",
        "source",
        "type"
      ],
      "type": "object"
    },
    "IModPackSourceInfo": {
      "defaultProperties": [
      ],
      "properties": {
        "fileExpression": {
          "type": "string"
        },
        "fileId": {
          "type": "number"
        },
        "fileSize": {
          "type": "number"
        },
        "instructions": {
          "type": "string"
        },
        "logicalFilename": {
          "type": "string"
        },
        "md5": {
          "type": "string"
        },
        "modId": {
          "type": "number"
        },
        "type": {
          "$ref": "#/definitions/SourceType"
        },
        "updatePolicy": {
          "$ref": "#/definitions/UpdatePolicy"
        },
        "url": {
          "type": "string"
        }
      },
      "required": [
        "type"
      ],
      "type": "object"
    },
    "IModReference": {
      "defaultProperties": [
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "fileExpression": {
          "type": "string"
        },
        "fileMD5": {
          "type": "string"
        },
        "fileSize": {
          "type": "number"
        },
        "gameId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "logicalFileName": {
          "type": "string"
        },
        "repo": {
          "allOf": [
            {
              "defaultProperties": [
              ],
              "properties": {
                "repository": {
                  "type": "string"
                }
              },
              "required": [
                "repository"
              ],
              "type": "object"
            },
            {
              "$ref": "#/definitions/IModRepoId"
            }
          ]
        },
        "tag": {
          "type": "string"
        },
        "versionMatch": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "IModRepoId": {
      "defaultProperties": [
      ],
      "properties": {
        "fileId": {
          "type": "string"
        },
        "gameId": {
          "type": "string"
        },
        "modId": {
          "type": "string"
        }
      },
      "required": [
        "fileId"
      ],
      "type": "object"
    },
    "IUserlistEntry": {
      "defaultProperties": [
      ],
      "properties": {
        "after": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "after",
        "name"
      ],
      "type": "object"
    },
    "RuleType": {
      "enum": [
        "after",
        "before",
        "conflicts",
        "provides",
        "recommends",
        "requires"
      ],
      "type": "string"
    },
    "SourceType": {
      "enum": [
        "browse",
        "direct",
        "manual",
        "bundle",
        "nexus"
      ],
      "type": "string"
    },
    "UpdatePolicy": {
      "enum": [
        "exact",
        "latest",
        "prefer"
      ],
      "type": "string"
    }
  },
  "properties": {
    "info": {
      "$ref": "#/definitions/IModPackInfo"
    },
    "modRules": {
      "items": {
        "$ref": "#/definitions/IModPackModRule"
      },
      "type": "array"
    },
    "mods": {
      "items": {
        "$ref": "#/definitions/IModPackMod"
      },
      "type": "array"
    },
    "pluginRules": {
      "$ref": "#/definitions/IGamebryoRules"
    },
    "plugins": {
      "items": {
        "defaultProperties": [
        ],
        "properties": {
          "enabled": {
            "type": "boolean"
          },
          "name": {
            "type": "string"
          }
        },
        "required": [
          "enabled",
          "name"
        ],
        "type": "object"
      },
      "type": "array"
    }
  },
  "required": [
    "info",
    "modRules",
    "mods"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isIModPack = ajv.compile(IModPackSchema) as ValidateFunction<IModPack>;
export default function validate(value: unknown): IModPack {
  if (isIModPack(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isIModPack.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'IModPack'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
