name: Test Build

on:
  push:
    branches: [ main, master, fix-node22 ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-windows:
    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [22.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Run full build
      run: yarn build
    
    - name: Validate build outputs (Windows)
      run: yarn test:build

    - name: Run unit tests
      run: yarn test
